set_property SRC_FILE_INFO {cfile:c:/Users/a/Desktop/MoatazProject/project_1/project_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_PmodHYGRO_0_1/pmod_design_with_uart_PmodHYGRO_0_1_board.xdc rfile:../../../project_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_PmodHYGRO_0_1/pmod_design_with_uart_PmodHYGRO_0_1_board.xdc id:1 order:EARLY used_in_board:yes scoped_inst:inst prop_thru_buffer:yes} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN {JC1} [get_ports Pmod_out_pin1_t]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN {JC2} [get_ports Pmod_out_pin2_t]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN {JC7} [get_ports Pmod_out_pin7_t]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN {JC8} [get_ports Pmod_out_pin8_t]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN {JC9} [get_ports Pmod_out_pin9_t]
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PART_PIN {JC10} [get_ports Pmod_out_pin10_t]
