# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Emphasis_B/Labs/Lab_5/Lab_5_Exercise_2/Lab_5_Exercise_2.srcs/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_2/pmod_design_with_uart_axi_gpio_0_2.xci
# IP: The module: 'pmod_design_with_uart_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Emphasis_B/Labs/Lab_5/Lab_5_Exercise_2/Lab_5_Exercise_2.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_2/pmod_design_with_uart_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Emphasis_B/Labs/Lab_5/Lab_5_Exercise_2/Lab_5_Exercise_2.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_2/pmod_design_with_uart_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Emphasis_B/Labs/Lab_5/Lab_5_Exercise_2/Lab_5_Exercise_2.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_2/pmod_design_with_uart_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Emphasis_B/Labs/Lab_5/Lab_5_Exercise_2/Lab_5_Exercise_2.srcs/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_2/pmod_design_with_uart_axi_gpio_0_2.xci
# IP: The module: 'pmod_design_with_uart_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Emphasis_B/Labs/Lab_5/Lab_5_Exercise_2/Lab_5_Exercise_2.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_2/pmod_design_with_uart_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Emphasis_B/Labs/Lab_5/Lab_5_Exercise_2/Lab_5_Exercise_2.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_2/pmod_design_with_uart_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Emphasis_B/Labs/Lab_5/Lab_5_Exercise_2/Lab_5_Exercise_2.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_2/pmod_design_with_uart_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
