# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Nexys-A7-100T-Master.xdc

# Block Designs: bd/pmod_design_with_uart/pmod_design_with_uart.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart || ORIG_REF_NAME==pmod_design_with_uart} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_PmodTMP3_0_0/pmod_design_with_uart_PmodTMP3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_PmodTMP3_0_0 || ORIG_REF_NAME==pmod_design_with_uart_PmodTMP3_0_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_clk_wiz_1_0/pmod_design_with_uart_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_clk_wiz_1_0 || ORIG_REF_NAME==pmod_design_with_uart_clk_wiz_1_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_mdm_1_0/pmod_design_with_uart_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_mdm_1_0 || ORIG_REF_NAME==pmod_design_with_uart_mdm_1_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_0/pmod_design_with_uart_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_microblaze_0_0 || ORIG_REF_NAME==pmod_design_with_uart_microblaze_0_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_intc_0/pmod_design_with_uart_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_microblaze_0_axi_intc_0 || ORIG_REF_NAME==pmod_design_with_uart_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_xbar_0/pmod_design_with_uart_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_xbar_0 || ORIG_REF_NAME==pmod_design_with_uart_xbar_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_periph_0/pmod_design_with_uart_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_microblaze_0_axi_periph_0 || ORIG_REF_NAME==pmod_design_with_uart_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_dlmb_v10_0/pmod_design_with_uart_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_dlmb_v10_0 || ORIG_REF_NAME==pmod_design_with_uart_dlmb_v10_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_ilmb_v10_0/pmod_design_with_uart_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_ilmb_v10_0 || ORIG_REF_NAME==pmod_design_with_uart_ilmb_v10_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_dlmb_bram_if_cntlr_0/pmod_design_with_uart_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==pmod_design_with_uart_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_ilmb_bram_if_cntlr_0/pmod_design_with_uart_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==pmod_design_with_uart_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_lmb_bram_0/pmod_design_with_uart_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_lmb_bram_0 || ORIG_REF_NAME==pmod_design_with_uart_lmb_bram_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_xlconcat_0/pmod_design_with_uart_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_microblaze_0_xlconcat_0 || ORIG_REF_NAME==pmod_design_with_uart_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_rst_clk_wiz_1_100M_0/pmod_design_with_uart_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==pmod_design_with_uart_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_uartlite_0_0/pmod_design_with_uart_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_axi_uartlite_0_0 || ORIG_REF_NAME==pmod_design_with_uart_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_1/pmod_design_with_uart_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_axi_gpio_0_1 || ORIG_REF_NAME==pmod_design_with_uart_axi_gpio_0_1} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_PmodHYGRO_0_1/pmod_design_with_uart_PmodHYGRO_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_PmodHYGRO_0_1 || ORIG_REF_NAME==pmod_design_with_uart_PmodHYGRO_0_1} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_axi_gpio_0_2/pmod_design_with_uart_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_axi_gpio_0_2 || ORIG_REF_NAME==pmod_design_with_uart_axi_gpio_0_2} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_PmodCLS_0_3/pmod_design_with_uart_PmodCLS_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_PmodCLS_0_3 || ORIG_REF_NAME==pmod_design_with_uart_PmodCLS_0_3} -quiet] -quiet

# IP: bd/pmod_design_with_uart/ip/pmod_design_with_uart_PmodPIR_0_0/pmod_design_with_uart_PmodPIR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_design_with_uart_PmodPIR_0_0 || ORIG_REF_NAME==pmod_design_with_uart_PmodPIR_0_0} -quiet] -quiet

# XDC: c:/Users/a/Desktop/MoatazProject/project_1/project_1.gen/sources_1/bd/pmod_design_with_uart/pmod_design_with_uart_ooc.xdc
