set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk]
set_property PACKAGE_PIN J17 [get_ports {anode[0]}]
set_property PACKAGE_PIN T9 [get_ports {anodeothr[0]}]
set_property PACKAGE_PIN J18 [get_ports {anode[1]}]
set_property PACKAGE_PIN T10 [get_ports {cathode[0]}]
set_property PACKAGE_PIN R10 [get_ports {cathode[1]}]
set_property PACKAGE_PIN K16 [get_ports {cathode[2]}]
set_property PACKAGE_PIN K13 [get_ports {cathode[3]}]
set_property PACKAGE_PIN P15 [get_ports {cathode[4]}]
set_property PACKAGE_PIN L18 [get_ports {cathode[6]}]
set_property PACKAGE_PIN T11 [get_ports {cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeothr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeothr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeothr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeothr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeothr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodeothr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
set_property PACKAGE_PIN J14 [get_ports {anodeothr[1]}]
set_property PACKAGE_PIN P14 [get_ports {anodeothr[2]}]
set_property PACKAGE_PIN T14 [get_ports {anodeothr[3]}]
set_property PACKAGE_PIN K2 [get_ports {anodeothr[4]}]
set_property PACKAGE_PIN U13 [get_ports {anodeothr[5]}]

set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {digit1[0]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {digit1[1]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {digit1[2]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {digit1[3]}]

