# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Emphasis_B/project_1/project_1.srcs/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_intc_0/pmod_design_with_uart_microblaze_0_axi_intc_0.xci
# IP: The module: 'pmod_design_with_uart_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Emphasis_B/project_1/project_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_intc_0/pmod_design_with_uart_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Emphasis_B/project_1/project_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_intc_0/pmod_design_with_uart_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Emphasis_B/project_1/project_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_intc_0/pmod_design_with_uart_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Emphasis_B/project_1/project_1.srcs/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_intc_0/pmod_design_with_uart_microblaze_0_axi_intc_0.xci
# IP: The module: 'pmod_design_with_uart_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Emphasis_B/project_1/project_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_intc_0/pmod_design_with_uart_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Emphasis_B/project_1/project_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_intc_0/pmod_design_with_uart_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Emphasis_B/project_1/project_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_microblaze_0_axi_intc_0/pmod_design_with_uart_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
