# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Emphasis_B/Labs/Lab_4/Lab_4_Exercise_1/Lab_4_Exercise_1.srcs/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_xbar_0/pmod_design_with_uart_xbar_0.xci
# IP: The module: 'pmod_design_with_uart_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Emphasis_B/Labs/Lab_4/Lab_4_Exercise_1/Lab_4_Exercise_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_xbar_0/pmod_design_with_uart_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Emphasis_B/Labs/Lab_4/Lab_4_Exercise_1/Lab_4_Exercise_1.srcs/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_xbar_0/pmod_design_with_uart_xbar_0.xci
# IP: The module: 'pmod_design_with_uart_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Emphasis_B/Labs/Lab_4/Lab_4_Exercise_1/Lab_4_Exercise_1.gen/sources_1/bd/pmod_design_with_uart/ip/pmod_design_with_uart_xbar_0/pmod_design_with_uart_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pmod_design_with_uart_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
